In [1]:
import numpy as np

In [2]:
# From a Python list
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))      # <class 'numpy.ndarray'>

# Multi-dimensional array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [3]:
import numpy as np

# From a Python list
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))      # <class 'numpy.ndarray'>

# Multi-dimensional array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)


[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]


In [1]:
print("Shape:", matrix.shape)
print("Size:", matrix.size)
print("Dimensions:", matrix.ndim)
print("Data Type:", matrix.dtype)


NameError: name 'matrix' is not defined

In [2]:
import numpy as np

# From a Python list
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))      # <class 'numpy.ndarray'>

# Multi-dimensional array
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)
print("Shape:", matrix.shape)
print("Size:", matrix.size)
print("Dimensions:", matrix.ndim)
print("Data Type:", matrix.dtype)


[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Size: 6
Dimensions: 2
Data Type: int32


In [3]:
zeros = np.zeros((2, 3))
ones = np.ones((3, 2))
range_arr = np.arange(0, 10, 2)
random_arr = np.random.randint(1, 100, (2, 3))

print("Zeros:\n", zeros)
print("Ones:\n", ones)
print("Range:\n", range_arr)
print("Random:\n", random_arr)


Zeros:
 [[0. 0. 0.]
 [0. 0. 0.]]
Ones:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]
Range:
 [0 2 4 6 8]
Random:
 [[26 92 69]
 [38 80 11]]


In [4]:
a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print(a + b)      # element-wise addition
print(a * b)      # element-wise multiplication
print(a ** 2)     # square each element
print(a.mean())   # average
print(np.sqrt(b)) # square root


[11 22 33 44]
[ 10  40  90 160]
[ 1  4  9 16]
2.5
[3.16227766 4.47213595 5.47722558 6.32455532]


In [5]:
arr = np.array([10, 20, 30, 40, 50])
print(arr[1:4])   # [20 30 40]
print(arr[:3])    # [10 20 30]
print(arr[-2:])   # [40 50]

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(matrix[0, 2])     # single element → 3
print(matrix[1:, 1:])   # sub-matrix


[20 30 40]
[10 20 30]
[40 50]
3
[[5 6]
 [8 9]]


In [6]:
import time

# Python list
my_list = list(range(1_000_000))
start = time.time()
result = [x * 2 for x in my_list]
print("List time:", round(time.time() - start, 4))

# NumPy array
my_array = np.arange(1_000_000)
start = time.time()
result = my_array * 2
print("NumPy time:", round(time.time() - start, 4))


List time: 0.0493
NumPy time: 0.0167


In [7]:
arr = np.array([10, 20, 30, 40, 50])

print("Mean:", np.mean(arr))
print("Median:", np.median(arr))
print("Standard Deviation:", np.std(arr))
print("Sum:", np.sum(arr))
print("Min:", np.min(arr))
print("Max:", np.max(arr))


Mean: 30.0
Median: 30.0
Standard Deviation: 14.142135623730951
Sum: 150
Min: 10
Max: 50


In [9]:
arr= np.arange(1,100)
print("Mean", np.mean(arr))
print("median", np.median(arr))
print("standard deviation" , np.std(arr))

Mean 50.0
median 50.0
standard deviation 28.577380332470412


In [12]:
random_arr = np.random.randint(1, 100, (3, 3))
print ("max", np.max(random_arr))
print ("min", np.min(random_arr))

max 76
min 22
